{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Meshroom + GPU for Photogrammetry",
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/1900690/kyouyu/blob/main/Meshroom_%2B_GPU_for_Photogrammetry.8.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "GV0aPgMN8PWY"
      },
      "source": [
        "#事前準備\n",
        "\n",
        "ランタイムをGPUに変更\n",
        "\n",
        "ツールバー＞ランタイム＞ランタイムのタイプを変更＞ハードウェアアクセラレータをGPUに変更"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Fn4dL7Sl8Fca",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "da4c62b8-387a-42cd-bbc7-7b8fb37e35dc"
      },
      "source": [
        "#GPUがあるかどうかチェック\n",
        "import tensorflow as tf\n",
        "device_name = tf.test.gpu_device_name()\n",
        "if device_name != '/device:GPU:0':\n",
        "  raise SystemError('GPU device not found')\n",
        "print('Found GPU at: {}'.format(device_name))"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Found GPU at: /device:GPU:0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "0eYTT15F8kqc"
      },
      "source": [
        "データの置き場所であるグーグルドライブをマウント"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "qetKvXVK8vWI",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "4d87bbfc-3b6b-4e7e-ab07-5721c5b31182"
      },
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Mounted at /content/drive\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Uw4xpkaiPZZd"
      },
      "source": [
        "ドライブからデータをコピーし、解凍して名前をmy_datasetに変更。"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#ドライブから画像の入ったzipファイルをコピー\n",
        "!cp /content/drive/My\\ Drive/chokobomag.zip .\n",
        "\n",
        "#zipファイルを解凍(ログを出さない)\n",
        "! unzip -q chokobomag.zip\n",
        "\n",
        "#zipファイルの名前を変更\n",
        "import os\n",
        "os.rename('chokobomag','my_dataset')"
      ],
      "metadata": {
        "id": "Idb0ESZXRTaT"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "#ブッダ画像でテスト\n",
        "#!git clone https://github.com/alicevision/dataset_buddha\n",
        "#!zip -q \"buddha.zip\" -r \"buddha\"\n",
        "#! unzip -q buddha.zip\n",
        "#ドライブから画像の入ったzipファイルをコピー\n",
        "#!cp /content/drive/My\\ Drive/buddha.zip .\n",
        "#zipファイルを解凍(ログを出さない)\n",
        "#! unzip -q buddha.zip\n",
        "#zipファイルの名前を変更\n",
        "#import os\n",
        "#os.rename('buddha','my_dataset')"
      ],
      "metadata": {
        "id": "6vHvUlMbAx6q"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "8qj3sOUyPQ37",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "0bce05fb-ecaa-4112-99ec-4a49f6fa4bce"
      },
      "source": [
        "#Meshroomをダウンロード\n",
        "!wget -N https://github.com/alicevision/meshroom/releases/download/v2019.1.0/Meshroom-2019.1.0-linux.tar.gz\n",
        "!mkdir meshroom\n",
        "!tar xzf Meshroom-2019.1.0-linux.tar.gz -C ./meshroom"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "--2022-02-24 01:01:26--  https://github.com/alicevision/meshroom/releases/download/v2019.1.0/Meshroom-2019.1.0-linux.tar.gz\n",
            "Resolving github.com (github.com)... 140.82.114.4\n",
            "Connecting to github.com (github.com)|140.82.114.4|:443... connected.\n",
            "HTTP request sent, awaiting response... 302 Found\n",
            "Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/34405381/ac2a6000-44ad-11e9-9c7e-7405269e659a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220224%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220224T010126Z&X-Amz-Expires=300&X-Amz-Signature=340786e9fed73d9afbfb9a9d2060b8b77109dda96cf55384252acef0d4a68d64&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=34405381&response-content-disposition=attachment%3B%20filename%3DMeshroom-2019.1.0-linux.tar.gz&response-content-type=application%2Foctet-stream [following]\n",
            "--2022-02-24 01:01:26--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/34405381/ac2a6000-44ad-11e9-9c7e-7405269e659a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220224%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220224T010126Z&X-Amz-Expires=300&X-Amz-Signature=340786e9fed73d9afbfb9a9d2060b8b77109dda96cf55384252acef0d4a68d64&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=34405381&response-content-disposition=attachment%3B%20filename%3DMeshroom-2019.1.0-linux.tar.gz&response-content-type=application%2Foctet-stream\n",
            "Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...\n",
            "Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.\n",
            "HTTP request sent, awaiting response... 200 OK\n",
            "Length: 357259007 (341M) [application/octet-stream]\n",
            "Saving to: ‘Meshroom-2019.1.0-linux.tar.gz’\n",
            "\n",
            "Meshroom-2019.1.0-l 100%[===================>] 340.71M   136MB/s    in 2.5s    \n",
            "\n",
            "2022-02-24 01:01:29 (136 MB/s) - ‘Meshroom-2019.1.0-linux.tar.gz’ saved [357259007/357259007]\n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Lop_Mdde9oaH"
      },
      "source": [
        "#フォトグラメトリスタート"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "8Bnjh20K9aJm",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "4f151ac4-fe72-4935-fd63-3866558d0df6"
      },
      "source": [
        "#稼働時間計測\n",
        "%%time\n",
        "!mkdir ./object_out\n",
        "!./meshroom/Meshroom-2019.1.0/meshroom_photogrammetry --input ./my_dataset --output ./object_out"
      ],
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing\n",
            "Program called with the following parameters:\n",
            " * allowSingleView = 1\n",
            " * defaultCameraModel = \"\" (default)\n",
            " * defaultFieldOfView = 45\n",
            " * defaultFocalLengthPix = -1 (default)\n",
            " * defaultIntrinsic = \"\" (default)\n",
            " * groupCameraFallback =  Unknown Type \"20EGroupCameraFallback\"\n",
            " * imageFolder = \"\" (default)\n",
            " * input = \"/tmp/tmpsg479rxw/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm\"\n",
            " * output = \"/tmp/tmpsg479rxw/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm\"\n",
            " * sensorDatabase = \"/content/meshroom/Meshroom-2019.1.0/aliceVision/share/aliceVision/cameraSensors.db\"\n",
            " * verboseLevel = \"info\"\n",
            "\n",
            "[05:41:24.019220][info] CameraInit report:\n",
            "\t- # views listed: 42\n",
            "\t   - # views with an initialized intrinsic listed: 42\n",
            "\t   - # views without metadata (with a default intrinsic): 0\n",
            "\t- # intrinsics listed: 1\n",
            "Nodes to execute:  ['CameraInit_1', 'FeatureExtraction_1', 'ImageMatching_1', 'FeatureMatching_1', 'StructureFromMotion_1', 'PrepareDenseScene_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1', 'Publish_1']\n",
            "\n",
            "[1/12] CameraInit\n",
            "Exception in thread Thread-1:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104695 0 3799202 55432 56110 0 3302736 27819 0 37189 87712 0 0 0 0 399 4460\\n'\n",
            "\n",
            " - commandLine: aliceVision_cameraInit  --sensorDatabase \"/content/meshroom/Meshroom-2019.1.0/aliceVision/share/aliceVision/cameraSensors.db\" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output \"/tmp/MeshroomCache/CameraInit/e2ea2dcda52aa32ac1261483e0deed0bce8cf096/cameraInit.sfm\" --allowSingleView 1  --input \"/tmp/MeshroomCache/CameraInit/e2ea2dcda52aa32ac1261483e0deed0bce8cf096//viewpoints.sfm\"\n",
            " - logFile: /tmp/MeshroomCache/CameraInit/e2ea2dcda52aa32ac1261483e0deed0bce8cf096/log\n",
            " - elapsed time: 0:00:00.076311\n",
            "\n",
            "[2/12](1/2) FeatureExtraction\n",
            " - commandLine: aliceVision_featureExtraction  --input \"/tmp/MeshroomCache/CameraInit/e2ea2dcda52aa32ac1261483e0deed0bce8cf096/cameraInit.sfm\" --describerTypes sift --describerPreset normal --forceCpuExtraction True --verboseLevel info --output \"/tmp/MeshroomCache/FeatureExtraction/88a358aab9e433784957b07636366c740fb047c1\" --rangeStart 0 --rangeSize 40\n",
            " - logFile: /tmp/MeshroomCache/FeatureExtraction/88a358aab9e433784957b07636366c740fb047c1/0.log\n",
            "Exception in thread Thread-2:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104696 0 3799330 55432 56114 0 3302768 27819 0 37193 87712 0 0 0 0 399 4460\\n'\n",
            "\n",
            " - elapsed time: 0:05:35.163508\n",
            "\n",
            "[2/12](2/2) FeatureExtraction\n",
            " - commandLine: aliceVision_featureExtraction  --input \"/tmp/MeshroomCache/CameraInit/e2ea2dcda52aa32ac1261483e0deed0bce8cf096/cameraInit.sfm\" --describerTypes sift --describerPreset normal --forceCpuExtraction True --verboseLevel info --output \"/tmp/MeshroomCache/FeatureExtraction/88a358aab9e433784957b07636366c740fb047c1\" --rangeStart 40 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/FeatureExtraction/88a358aab9e433784957b07636366c740fb047c1/1.log\n",
            "Exception in thread Thread-3:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104696 0 3799330 55432 57386 0 3443936 28628 0 37680 88868 0 0 0 0 519 4806\\n'\n",
            "\n",
            " - elapsed time: 0:00:15.125514\n",
            "\n",
            "[3/12] ImageMatching\n",
            " - commandLine: aliceVision_imageMatching  --input \"/tmp/MeshroomCache/CameraInit/e2ea2dcda52aa32ac1261483e0deed0bce8cf096/cameraInit.sfm\" --featuresFolders \"/tmp/MeshroomCache/FeatureExtraction/88a358aab9e433784957b07636366c740fb047c1\" --tree \"/content/meshroom/Meshroom-2019.1.0/aliceVision/share/aliceVision/vlfeat_K80L3.SIFT.tree\" --weights \"\" --minNbImages 200 --maxDescriptors 500 --nbMatches 50 --verboseLevel info --output \"/tmp/MeshroomCache/ImageMatching/aad7d796368a5e289aad7e6b4b2b488446c42b39/imageMatches.txt\" \n",
            " - logFile: /tmp/MeshroomCache/ImageMatching/aad7d796368a5e289aad7e6b4b2b488446c42b39/log\n",
            "Exception in thread Thread-4:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104696 0 3799330 55432 57428 0 3450464 28657 0 37703 88911 0 0 0 0 525 4820\\n'\n",
            "\n",
            " - elapsed time: 0:00:00.030454\n",
            "\n",
            "[4/12](1/3) FeatureMatching\n",
            " - commandLine: aliceVision_featureMatching  --input \"/tmp/MeshroomCache/CameraInit/e2ea2dcda52aa32ac1261483e0deed0bce8cf096/cameraInit.sfm\" --featuresFolders \"/tmp/MeshroomCache/FeatureExtraction/88a358aab9e433784957b07636366c740fb047c1\" --imagePairsList \"/tmp/MeshroomCache/ImageMatching/aad7d796368a5e289aad7e6b4b2b488446c42b39/imageMatches.txt\" --describerTypes sift --photometricMatchingMethod ANN_L2 --geometricEstimator acransac --geometricFilterType fundamental_matrix --distanceRatio 0.8 --maxIteration 2048 --geometricError 0.0 --maxMatches 0 --savePutativeMatches False --guidedMatching False --exportDebugFiles False --verboseLevel info --output \"/tmp/MeshroomCache/FeatureMatching/238c1872ac58ca7e1b2eabc1ff3b1dcb9870edab\" --rangeStart 0 --rangeSize 20\n",
            " - logFile: /tmp/MeshroomCache/FeatureMatching/238c1872ac58ca7e1b2eabc1ff3b1dcb9870edab/0.log\n",
            "Exception in thread Thread-5:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104696 0 3799330 55432 57431 0 3450488 28657 0 37705 88911 0 0 0 0 525 4820\\n'\n",
            "\n",
            " - elapsed time: 0:05:16.297410\n",
            "\n",
            "[4/12](2/3) FeatureMatching\n",
            " - commandLine: aliceVision_featureMatching  --input \"/tmp/MeshroomCache/CameraInit/e2ea2dcda52aa32ac1261483e0deed0bce8cf096/cameraInit.sfm\" --featuresFolders \"/tmp/MeshroomCache/FeatureExtraction/88a358aab9e433784957b07636366c740fb047c1\" --imagePairsList \"/tmp/MeshroomCache/ImageMatching/aad7d796368a5e289aad7e6b4b2b488446c42b39/imageMatches.txt\" --describerTypes sift --photometricMatchingMethod ANN_L2 --geometricEstimator acransac --geometricFilterType fundamental_matrix --distanceRatio 0.8 --maxIteration 2048 --geometricError 0.0 --maxMatches 0 --savePutativeMatches False --guidedMatching False --exportDebugFiles False --verboseLevel info --output \"/tmp/MeshroomCache/FeatureMatching/238c1872ac58ca7e1b2eabc1ff3b1dcb9870edab\" --rangeStart 20 --rangeSize 20\n",
            " - logFile: /tmp/MeshroomCache/FeatureMatching/238c1872ac58ca7e1b2eabc1ff3b1dcb9870edab/1.log\n",
            "Exception in thread Thread-6:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104696 0 3799330 55432 57935 0 3473240 28964 0 38025 89428 0 0 0 0 637 5031\\n'\n",
            "\n",
            " - elapsed time: 0:01:56.020726\n",
            "\n",
            "[4/12](3/3) FeatureMatching\n",
            " - commandLine: aliceVision_featureMatching  --input \"/tmp/MeshroomCache/CameraInit/e2ea2dcda52aa32ac1261483e0deed0bce8cf096/cameraInit.sfm\" --featuresFolders \"/tmp/MeshroomCache/FeatureExtraction/88a358aab9e433784957b07636366c740fb047c1\" --imagePairsList \"/tmp/MeshroomCache/ImageMatching/aad7d796368a5e289aad7e6b4b2b488446c42b39/imageMatches.txt\" --describerTypes sift --photometricMatchingMethod ANN_L2 --geometricEstimator acransac --geometricFilterType fundamental_matrix --distanceRatio 0.8 --maxIteration 2048 --geometricError 0.0 --maxMatches 0 --savePutativeMatches False --guidedMatching False --exportDebugFiles False --verboseLevel info --output \"/tmp/MeshroomCache/FeatureMatching/238c1872ac58ca7e1b2eabc1ff3b1dcb9870edab\" --rangeStart 40 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/FeatureMatching/238c1872ac58ca7e1b2eabc1ff3b1dcb9870edab/2.log\n",
            "Exception in thread Thread-7:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104696 0 3799330 55432 58129 0 3476528 29082 0 38157 89632 0 0 0 0 683 5117\\n'\n",
            "\n",
            " - elapsed time: 0:00:00.589171\n",
            "\n",
            "[5/12] StructureFromMotion\n",
            " - commandLine: aliceVision_incrementalSfM  --input \"/tmp/MeshroomCache/CameraInit/e2ea2dcda52aa32ac1261483e0deed0bce8cf096/cameraInit.sfm\" --featuresFolders \"/tmp/MeshroomCache/FeatureExtraction/88a358aab9e433784957b07636366c740fb047c1\" --matchesFolders \"/tmp/MeshroomCache/FeatureMatching/238c1872ac58ca7e1b2eabc1ff3b1dcb9870edab\" --describerTypes sift --localizerEstimator acransac --localizerEstimatorMaxIterations 4096 --localizerEstimatorError 0.0 --lockScenePreviouslyReconstructed False --useLocalBA True --localBAGraphDistance 1 --maxNumberOfMatches 0 --minInputTrackLength 2 --minNumberOfObservationsForTriangulation 2 --minAngleForTriangulation 3.0 --minAngleForLandmark 2.0 --maxReprojectionError 4.0 --minAngleInitialPair 5.0 --maxAngleInitialPair 40.0 --useOnlyMatchesFromInputFolder False --useRigConstraint True --lockAllIntrinsics False --initialPairA \"\" --initialPairB \"\" --interFileExtension .abc --verboseLevel info --output \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --outputViewsAndPoses \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/cameras.sfm\" --extraInfoFolder \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470\" \n",
            " - logFile: /tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/log\n",
            "Exception in thread Thread-8:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104696 0 3799330 55432 58151 0 3477272 29090 0 38161 89640 0 0 0 0 683 5117\\n'\n",
            "\n",
            " - elapsed time: 0:01:07.179482\n",
            "\n",
            "[6/12](1/2) PrepareDenseScene\n",
            " - commandLine: aliceVision_prepareDenseScene  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --outputFileType exr --saveMetadata True --saveMatricesTxtFiles False --verboseLevel info --output \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --rangeStart 0 --rangeSize 40\n",
            " - logFile: /tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769/0.log\n",
            "Exception in thread Thread-9:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104697 0 3799570 55432 58354 0 3493016 29222 0 38258 89835 0 0 0 0 715 5179\\n'\n",
            "\n",
            " - elapsed time: 0:00:56.544189\n",
            "\n",
            "[6/12](2/2) PrepareDenseScene\n",
            " - commandLine: aliceVision_prepareDenseScene  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --outputFileType exr --saveMetadata True --saveMatricesTxtFiles False --verboseLevel info --output \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --rangeStart 40 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769/1.log\n",
            "Exception in thread Thread-10:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104701 0 3799786 55437 63602 0 6214136 46406 0 42734 109564 0 0 0 0 742 7720\\n'\n",
            "\n",
            " - elapsed time: 0:00:02.867362\n",
            "\n",
            "[7/12](1/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 0 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/0.log\n",
            "Exception in thread Thread-11:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104701 0 3799786 55437 63632 0 6214376 46414 0 42744 109576 0 0 0 0 744 7725\\n'\n",
            "\n",
            " - elapsed time: 0:01:33.577487\n",
            "\n",
            "[7/12](2/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 3 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/1.log\n",
            "Exception in thread Thread-12:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104933 0 3801986 55803 63970 0 6468264 48230 0 43634 112215 0 0 0 0 783 8181\\n'\n",
            "\n",
            " - elapsed time: 0:01:53.322659\n",
            "\n",
            "[7/12](3/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 6 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/2.log\n",
            "Exception in thread Thread-13:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104949 0 3802242 55820 64177 0 6511968 48469 0 43826 112577 0 0 0 0 827 8287\\n'\n",
            "\n",
            " - elapsed time: 0:01:23.623887\n",
            "\n",
            "[7/12](4/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 9 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/3.log\n",
            "Exception in thread Thread-14:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104949 0 3802242 55820 64387 0 6597224 48805 0 44026 113038 0 0 0 0 860 8412\\n'\n",
            "\n",
            " - elapsed time: 0:01:54.874832\n",
            "\n",
            "[7/12](5/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 12 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/4.log\n",
            "Exception in thread Thread-15:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104950 0 3802250 55820 64591 0 6661816 49068 0 44187 113394 0 0 0 0 903 8505\\n'\n",
            "\n",
            " - elapsed time: 0:01:12.281761\n",
            "\n",
            "[7/12](6/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 15 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/5.log\n",
            "Exception in thread Thread-16:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104950 0 3802250 55820 64802 0 6726352 49346 0 44348 113775 0 0 0 0 933 8608\\n'\n",
            "\n",
            " - elapsed time: 0:01:46.224690\n",
            "\n",
            "[7/12](7/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 18 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/6.log\n",
            "Exception in thread Thread-17:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104950 0 3802250 55820 65041 0 6791200 49658 0 44534 114195 0 0 0 0 975 8715\\n'\n",
            "\n",
            " - elapsed time: 0:01:34.386871\n",
            "\n",
            "[7/12](8/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 21 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/7.log\n",
            "Exception in thread Thread-18:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104955 0 3802322 55832 65246 0 6834832 49879 0 44694 114519 0 0 0 0 1014 8806\\n'\n",
            "\n",
            " - elapsed time: 0:01:53.267305\n",
            "\n",
            "[7/12](9/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 24 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/8.log\n",
            "Exception in thread Thread-19:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104958 0 3802450 55835 65510 0 6920696 50330 0 44929 115122 0 0 0 0 1062 8956\\n'\n",
            "\n",
            " - elapsed time: 0:01:45.580488\n",
            "\n",
            "[7/12](10/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 27 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/9.log\n",
            "Exception in thread Thread-20:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104986 0 3806042 55843 65751 0 7006632 50673 0 45116 115565 0 0 0 0 1103 9048\\n'\n",
            "\n",
            " - elapsed time: 0:01:40.169755\n",
            "\n",
            "[7/12](11/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 30 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/10.log\n",
            "Exception in thread Thread-21:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104986 0 3806042 55843 65936 0 7029168 50843 0 45258 115834 0 0 0 0 1142 9147\\n'\n",
            "\n",
            " - elapsed time: 0:01:39.194630\n",
            "\n",
            "[7/12](12/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 33 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/11.log\n",
            "Exception in thread Thread-22:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104986 0 3806042 55843 66130 0 7093760 51131 0 45442 116238 0 0 0 0 1181 9264\\n'\n",
            "\n",
            " - elapsed time: 0:01:57.012636\n",
            "\n",
            "[7/12](13/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 36 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/12.log\n",
            "Exception in thread Thread-23:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 104986 0 3806042 55843 66393 0 7179592 51534 0 45656 116777 0 0 0 0 1227 9399\\n'\n",
            "\n",
            " - elapsed time: 0:01:44.516365\n",
            "\n",
            "[7/12](14/14) DepthMap\n",
            " - commandLine: aliceVision_depthMapEstimation  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --rangeStart 39 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25/13.log\n",
            "Exception in thread Thread-24:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 105027 0 3810402 55967 66609 0 7223536 51750 0 45915 117206 0 0 0 0 1268 9488\\n'\n",
            "\n",
            " - elapsed time: 0:00:51.011209\n",
            "\n",
            "[8/12](1/5) DepthMapFilter\n",
            " - commandLine: aliceVision_depthMapFiltering  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --depthMapsFolder \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --minViewAngle 2.0 --maxViewAngle 70.0 --nNearestCams 10 --minNumOfConsistentCams 3 --minNumOfConsistentCamsWithLowSimilarity 4 --pixSizeBall 0 --pixSizeBallWithLowSimilarity 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMapFilter/7b64acbd61a4ecd53481a65fdf25bd7f591dd09a\" --rangeStart 0 --rangeSize 10\n",
            " - logFile: /tmp/MeshroomCache/DepthMapFilter/7b64acbd61a4ecd53481a65fdf25bd7f591dd09a/0.log\n",
            "Exception in thread Thread-25:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 105027 0 3810402 55967 66742 0 7265840 51932 0 45992 117425 0 0 0 0 1288 9525\\n'\n",
            "\n",
            " - elapsed time: 0:01:28.916650\n",
            "\n",
            "[8/12](2/5) DepthMapFilter\n",
            " - commandLine: aliceVision_depthMapFiltering  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --depthMapsFolder \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --minViewAngle 2.0 --maxViewAngle 70.0 --nNearestCams 10 --minNumOfConsistentCams 3 --minNumOfConsistentCamsWithLowSimilarity 4 --pixSizeBall 0 --pixSizeBallWithLowSimilarity 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMapFilter/7b64acbd61a4ecd53481a65fdf25bd7f591dd09a\" --rangeStart 10 --rangeSize 10\n",
            " - logFile: /tmp/MeshroomCache/DepthMapFilter/7b64acbd61a4ecd53481a65fdf25bd7f591dd09a/1.log\n",
            "Exception in thread Thread-26:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 105054 0 3815778 56023 66994 0 7312304 52170 0 46222 117819 0 0 0 0 1323 9625\\n'\n",
            "\n",
            " - elapsed time: 0:01:38.740713\n",
            "\n",
            "[8/12](3/5) DepthMapFilter\n",
            " - commandLine: aliceVision_depthMapFiltering  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --depthMapsFolder \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --minViewAngle 2.0 --maxViewAngle 70.0 --nNearestCams 10 --minNumOfConsistentCams 3 --minNumOfConsistentCamsWithLowSimilarity 4 --pixSizeBall 0 --pixSizeBallWithLowSimilarity 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMapFilter/7b64acbd61a4ecd53481a65fdf25bd7f591dd09a\" --rangeStart 20 --rangeSize 10\n",
            " - logFile: /tmp/MeshroomCache/DepthMapFilter/7b64acbd61a4ecd53481a65fdf25bd7f591dd09a/2.log\n",
            "Exception in thread Thread-27:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 105054 0 3815778 56023 67368 0 7475152 53082 0 46674 119035 0 0 0 0 1360 9929\\n'\n",
            "\n",
            " - elapsed time: 0:01:42.329098\n",
            "\n",
            "[8/12](4/5) DepthMapFilter\n",
            " - commandLine: aliceVision_depthMapFiltering  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --depthMapsFolder \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --minViewAngle 2.0 --maxViewAngle 70.0 --nNearestCams 10 --minNumOfConsistentCams 3 --minNumOfConsistentCamsWithLowSimilarity 4 --pixSizeBall 0 --pixSizeBallWithLowSimilarity 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMapFilter/7b64acbd61a4ecd53481a65fdf25bd7f591dd09a\" --rangeStart 30 --rangeSize 10\n",
            " - logFile: /tmp/MeshroomCache/DepthMapFilter/7b64acbd61a4ecd53481a65fdf25bd7f591dd09a/3.log\n",
            "Exception in thread Thread-28:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 105054 0 3815778 56023 67808 0 7659800 54008 0 47148 120287 0 0 0 0 1394 10255\\n'\n",
            "\n",
            " - elapsed time: 0:01:36.611463\n",
            "\n",
            "[8/12](5/5) DepthMapFilter\n",
            " - commandLine: aliceVision_depthMapFiltering  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --depthMapsFolder \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --minViewAngle 2.0 --maxViewAngle 70.0 --nNearestCams 10 --minNumOfConsistentCams 3 --minNumOfConsistentCamsWithLowSimilarity 4 --pixSizeBall 0 --pixSizeBallWithLowSimilarity 0 --verboseLevel info --output \"/tmp/MeshroomCache/DepthMapFilter/7b64acbd61a4ecd53481a65fdf25bd7f591dd09a\" --rangeStart 40 --rangeSize 3\n",
            " - logFile: /tmp/MeshroomCache/DepthMapFilter/7b64acbd61a4ecd53481a65fdf25bd7f591dd09a/4.log\n",
            "Exception in thread Thread-29:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 105054 0 3815778 56023 68272 0 7952248 55262 0 47715 122035 0 0 0 0 1428 10749\\n'\n",
            "\n",
            " - elapsed time: 0:00:13.036319\n",
            "\n",
            "[9/12] Meshing\n",
            " - commandLine: aliceVision_meshing  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --depthMapsFolder \"/tmp/MeshroomCache/DepthMap/fb17036209bc8e3f98a5591e2e1ad1c47df33f25\" --depthMapsFilterFolder \"/tmp/MeshroomCache/DepthMapFilter/7b64acbd61a4ecd53481a65fdf25bd7f591dd09a\" --estimateSpaceFromSfM True --estimateSpaceMinObservations 3 --estimateSpaceMinObservationAngle 10 --maxInputPoints 50000000 --maxPoints 5000000 --maxPointsPerVoxel 1000000 --minStep 2 --partitioning singleBlock --repartition multiResolution --angleFactor 15.0 --simFactor 15.0 --pixSizeMarginInitCoef 2.0 --pixSizeMarginFinalCoef 4.0 --voteMarginFactor 4.0 --contributeMarginFactor 2.0 --simGaussianSizeInit 10.0 --simGaussianSize 10.0 --minAngleThreshold 1.0 --refineFuse True --addLandmarksToTheDensePointCloud False --verboseLevel info --output \"/tmp/MeshroomCache/Meshing/56a0b06eb9e52d52a1b670f1b4495334114e5101/mesh.obj\" \n",
            " - logFile: /tmp/MeshroomCache/Meshing/56a0b06eb9e52d52a1b670f1b4495334114e5101/log\n",
            "Exception in thread Thread-30:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 105054 0 3815778 56023 68317 0 7952592 55272 0 47725 122050 0 0 0 0 1432 10754\\n'\n",
            "\n",
            " - elapsed time: 0:13:10.123636\n",
            "\n",
            "[10/12] MeshFiltering\n",
            " - commandLine: aliceVision_meshFiltering  --input \"/tmp/MeshroomCache/Meshing/56a0b06eb9e52d52a1b670f1b4495334114e5101/mesh.obj\" --removeLargeTrianglesFactor 60.0 --keepLargestMeshOnly False --iterations 5 --lambda 1.0 --verboseLevel info --output \"/tmp/MeshroomCache/MeshFiltering/e23c840e685d74468ffebe2757b548407e78c4d8/mesh.obj\" \n",
            " - logFile: /tmp/MeshroomCache/MeshFiltering/e23c840e685d74468ffebe2757b548407e78c4d8/log\n",
            "Exception in thread Thread-31:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 105971 0 3825306 60157 69461 0 8265776 56744 0 49247 128166 0 0 0 0 1699 11264\\n'\n",
            "\n",
            " - elapsed time: 0:00:11.701718\n",
            "\n",
            "[11/12] Texturing\n",
            " - commandLine: aliceVision_texturing  --input \"/tmp/MeshroomCache/StructureFromMotion/c445b84e4829973a88df4e154dfee34062843470/sfm.abc\" --imagesFolder \"/tmp/MeshroomCache/PrepareDenseScene/5b992addf6b8929843fc00183a825eda32cfd769\" --inputDenseReconstruction \"/tmp/MeshroomCache/Meshing/56a0b06eb9e52d52a1b670f1b4495334114e5101/denseReconstruction.bin\" --inputMesh \"/tmp/MeshroomCache/MeshFiltering/e23c840e685d74468ffebe2757b548407e78c4d8/mesh.obj\" --textureSide 8192 --downscale 2 --outputTextureFileType png --unwrapMethod Basic --fillHoles False --padding 15 --maxNbImagesForFusion 3 --bestScoreThreshold 0.0 --angleHardThreshold 90.0 --forceVisibleByAllVertices False --flipNormals False --visibilityRemappingMethod PullPush --verboseLevel info --output \"/tmp/MeshroomCache/Texturing/a1bc9396ee54d38598d850a105d0c355a4ec3dd4\" \n",
            " - logFile: /tmp/MeshroomCache/Texturing/a1bc9396ee54d38598d850a105d0c355a4ec3dd4/log\n",
            "Exception in thread Thread-32:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 105974 0 3825690 60161 69513 0 8266200 57109 1 49604 128884 0 0 0 0 1702 11613\\n'\n",
            "\n",
            " - elapsed time: 0:03:31.334619\n",
            "\n",
            "[12/12] Publish\n",
            "Publish\n",
            "Publish file /tmp/MeshroomCache/Texturing/a1bc9396ee54d38598d850a105d0c355a4ec3dd4/texturedMesh.obj into object_out/texturedMesh.obj\n",
            "Exception in thread Thread-33:\n",
            "Traceback (most recent call last):\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 206, in run\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 200, in updateStats\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 162, in update\n",
            "  File \"/opt/Meshroom/meshroom/core/stats.py\", line 52, in update\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py\", line 2131, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1121, in disk_io_counters\n",
            "  File \"/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py\", line 1094, in read_procfs\n",
            "ValueError: not sure how to interpret line '   7       0 loop0 126641 0 4078858 100113 70200 0 8683880 59080 1 63425 171352 0 0 0 0 1778 12158\\n'\n",
            "\n",
            "Publish file /tmp/MeshroomCache/Texturing/a1bc9396ee54d38598d850a105d0c355a4ec3dd4/texturedMesh.mtl into object_out/texturedMesh.mtl\n",
            "Publish file /tmp/MeshroomCache/Texturing/a1bc9396ee54d38598d850a105d0c355a4ec3dd4/texture_3.png into object_out/texture_3.png\n",
            "Publish file /tmp/MeshroomCache/Texturing/a1bc9396ee54d38598d850a105d0c355a4ec3dd4/texture_2.png into object_out/texture_2.png\n",
            "Publish file /tmp/MeshroomCache/Texturing/a1bc9396ee54d38598d850a105d0c355a4ec3dd4/texture_1.png into object_out/texture_1.png\n",
            "Publish file /tmp/MeshroomCache/Texturing/a1bc9396ee54d38598d850a105d0c355a4ec3dd4/texture_0.png into object_out/texture_0.png\n",
            "Publish end\n",
            " - elapsed time: 0:00:00.372369\n",
            "CPU times: user 20.2 s, sys: 3.33 s, total: 23.5 s\n",
            "Wall time: 1h 1min 33s\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "#colabの90分セッション切れ防止\n",
        "Google Colabを実行させるChromeブラウザでF12を押して、デベロッパーツールを開き、Consoleウィンドウで、次のように入力してEnterキーを押してください。\n",
        "\n",
        "※無限にランタイムの接続をやり直す。止めるにはタブを閉じる"
      ],
      "metadata": {
        "id": "T7IiJtW7QHl7"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "function ClickConnect(){\n",
        "  console.log(\"60sごとに再接続\");\n",
        "  document.querySelector(\"colab-connect-button\").click()}\n",
        "setInterval(ClickConnect,1000*60);"
      ],
      "metadata": {
        "id": "-2oVI9KsQJE8"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "# 結果を圧縮してダウンロード"
      ],
      "metadata": {
        "id": "LwQjRYECrVEG"
      }
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "wtz12QNl930T",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 139
        },
        "outputId": "3571a88e-51ac-442d-8770-008b8d6fe6fc"
      },
      "source": [
        "from google.colab import files\n",
        "!zip -r meshobject.zip ./object_out\n",
        "files.download('meshobject.zip')"
      ],
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "  adding: object_out/ (stored 0%)\n",
            "  adding: object_out/texture_3.png (deflated 3%)\n",
            "  adding: object_out/texture_2.png (deflated 0%)\n",
            "  adding: object_out/texture_1.png (deflated 0%)\n",
            "  adding: object_out/texturedMesh.mtl (deflated 72%)\n",
            "  adding: object_out/texturedMesh.obj (deflated 74%)\n",
            "  adding: object_out/texture_0.png (deflated 0%)\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "    async function download(id, filename, size) {\n",
              "      if (!google.colab.kernel.accessAllowed) {\n",
              "        return;\n",
              "      }\n",
              "      const div = document.createElement('div');\n",
              "      const label = document.createElement('label');\n",
              "      label.textContent = `Downloading \"${filename}\": `;\n",
              "      div.appendChild(label);\n",
              "      const progress = document.createElement('progress');\n",
              "      progress.max = size;\n",
              "      div.appendChild(progress);\n",
              "      document.body.appendChild(div);\n",
              "\n",
              "      const buffers = [];\n",
              "      let downloaded = 0;\n",
              "\n",
              "      const channel = await google.colab.kernel.comms.open(id);\n",
              "      // Send a message to notify the kernel that we're ready.\n",
              "      channel.send({})\n",
              "\n",
              "      for await (const message of channel.messages) {\n",
              "        // Send a message to notify the kernel that we're ready.\n",
              "        channel.send({})\n",
              "        if (message.buffers) {\n",
              "          for (const buffer of message.buffers) {\n",
              "            buffers.push(buffer);\n",
              "            downloaded += buffer.byteLength;\n",
              "            progress.value = downloaded;\n",
              "          }\n",
              "        }\n",
              "      }\n",
              "      const blob = new Blob(buffers, {type: 'application/binary'});\n",
              "      const a = document.createElement('a');\n",
              "      a.href = window.URL.createObjectURL(blob);\n",
              "      a.download = filename;\n",
              "      div.appendChild(a);\n",
              "      a.click();\n",
              "      div.remove();\n",
              "    }\n",
              "  "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "download(\"download_5e158e95-f038-42e6-89f5-3abcdc1068be\", \"meshobject.zip\", 83396761)"
            ]
          },
          "metadata": {}
        }
      ]
    }
  ]
}